//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupremeFiction.UI.SupremeRulerModdingTool.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupremeFiction.UI.SupremeRulerModdingTool.Core.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Missiles,,Unit Class,Pic Number,Tech Level,Year considered obsolete,Market avail.,Targettype,Move type,initiative,stealth,-,region code,equals 1,crew per squad,upgrade to,replaced by,refit to,-,move speed,-,?,?,tech prereq1,tech prereq1,days to build,cost to build,-,Ur Cost,Weight,-,-,movement range,,fuel cap,equals 1,warhead weight,att0,att1,att2,att3,att4,att5,att6,att7,att8,def0,def1,def2,def3,attrange0,attrange1,attrange2,attrange3,,,,,,,,,,,,,,,,,,,,,,-,,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,Strat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Missiles {
            get {
                return ResourceManager.GetString("Missiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SR5ID, ModelCode+EquipName, ClassNum, PicNum, (YearAvail - 1900), (OutOfProd - 1900), `market availability`, TargetType, MoveType, Initiative, StealthStr, CarrierCapacity, Regions, NumSquadInBatt, Crew, UGTo, ReplaceBy, RefitTo, AbandonTo, Speed, MisislePtsCapacity, SpotType1, SpotType2, TechReq1, TechReq2, DaysToBuild, Cost, IGCost, URCost, Weight, SupplyLevel, TransportCap, MoveRange, TurretArc, FuelCap, CombatTime, SupplyCap, SoftAttack, HardAttack, FortAttack, LowAirAttack, MidAirAttack, HighAirAttac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SR5ID {
            get {
                return ResourceManager.GetString("SR5ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // UNITS,Name,Unit Class,Pic Number,Tech Level,Year considered obsolete,Market avail.,Targettype,Move type,initiative,stealth,carrier capacity,region code,Battalion size,crew per squad,upgrade to,replaced by,refit to,-,move speed,missile capacity,spot type 1,spot type 2,tech prereq1,tech prereq2,days to build,cost to build,-,Ur Cost,Weight,-,cargo capacity,movement range,usused,fuel cap,combat time,ammo capacity,Soft,Hard,Fort,Close Air,Mid Air,High Air,Surface,Submerged,Close Combat,Ground Def,Air Def,Indi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNITS {
            get {
                return ResourceManager.GetString("UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // upgrades,,Unit Class,Pic Number,Tech Level,Year considered obsolete,Market avail.,Targettype,-,-,stealth,-,-,equals 1,crew per squad,upgrade to,replaced by,refit to,abandon too,-,-,spot type 1,spot type 1,tech prereq1,tech prereq1,days to build,cost to build,IG to build,Ur Cost,Weight,supply level,-,-,,-,combat time,ammo capacity,att0,att1,att2,att3,att4,att5,att6,att7,att8,def0,def1,def2,def3,attrange0,attrange1,attrange2,attrange3,,,,,,,,,,,,,,,,,,,,,,-,-,-,-,-,-,-,uHasProduction,supplymoveonly,Low Vis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
    }
}
